#! /bin/sh

[ -d 'app' ] || (echo "not in rails project directory" && exit 1)

SRV=freya.krupenik.com
FN=expenses-db-`date +"%Y%m%d%H%M%S"`
DMP=/tmp/$FN
DB="-U expenses expenses"
ECHO=/bin/echo

$ECHO -n "dumping remote database: " && ssh $SRV "pg_dump -cxO $DB | gzip - - > $DMP.gz" && $ECHO "done."
$ECHO -n "fetching dump file..." && (scp $SRV:$DMP.gz $DMP.gz && gunzip $DMP.gz); ssh $SRV "rm $DMP.gz"
$ECHO -n "populating local database: " && psql $DB < $DMP > /dev/null && rm $DMP && $ECHO "done."

